/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Mathlib.Algebra.Module.Equiv.Basic
public import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# Invariant vectors of a representation of a free group

A free group is generated by the image of `FreeGroup.of`, so a vector fixed by the action of
every free generator is fixed by the action of every group element.  This file records that
reduction for a representation of a free group by linear automorphisms.

## Main results

* `FreeGroup.forall_apply_eq_self_iff`: for `ρ : FreeGroup A →* (N ≃ₗ[R] N)` and `x : N`, the
  vector `x` is invariant under every element of `FreeGroup A` if and only if it is fixed by
  every free generator `FreeGroup.of a`.

The proof is `FreeGroup.induction_on`; nothing beyond Mathlib is used.
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false

namespace FreeGroup

/-- A vector in a representation of a free group is invariant exactly when it is fixed by every
free generator. -/
theorem forall_apply_eq_self_iff {A R N : Type*} [CommSemiring R]
    [AddCommMonoid N] [Module R N] (ρ : FreeGroup A →* (N ≃ₗ[R] N)) (x : N) :
    (∀ g, ρ g x = x) ↔ ∀ a, ρ (FreeGroup.of a) x = x := by
  constructor
  · exact fun h a ↦ h (FreeGroup.of a)
  · intro h g
    induction g using FreeGroup.induction_on with
    | C1 => simp
    | of a => exact h a
    | inv_of a ha =>
        rw [_root_.map_inv]
        calc
          (ρ (FreeGroup.of a))⁻¹ x =
              (ρ (FreeGroup.of a))⁻¹ (ρ (FreeGroup.of a) x) :=
            congrArg (fun y ↦ (ρ (FreeGroup.of a))⁻¹ y) ha.symm
          _ = x := by
            rw [← LinearEquiv.mul_apply]
            simp
    | mul g k hg hk =>
        simp only [_root_.map_mul, LinearEquiv.mul_apply, hk, hg]

end FreeGroup
