/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# Detecting primitive generators of cyclic subgroups

A homomorphism to the multiplicative copy of `ℤ` detects when an element of a cyclic subgroup
is already a generator.  For a free group, the exponent sum of a displayed free generator gives
the required detector.
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false

noncomputable section

namespace Subgroup

variable {G : Type*} [Group G]

/-- A cyclic subgroup containing an element detected primitively in `ℤ` is generated by that
element.  This is useful for identifying local monodromy images without choosing a preferred
fundamental-group generator. -/
theorem zpowers_eq_of_mem_of_multiplicativeInt_detector
    (g a : G) (chi : G →* Multiplicative ℤ)
    (hg : chi g = Multiplicative.ofAdd 1)
    (hmem : g ∈ zpowers a) :
    zpowers a = zpowers g := by
  obtain ⟨k, hk⟩ := mem_zpowers_iff.mp hmem
  have hmap := congrArg (fun z : Multiplicative ℤ ↦ z.toAdd)
    (congrArg chi hk)
  have hmul : k * (chi a).toAdd = 1 := by
    rw [map_zpow, hg] at hmap
    change k • (chi a).toAdd = 1 at hmap
    simpa only [smul_eq_mul] using hmap
  rcases (Int.mul_eq_one_iff_eq_one_or_neg_one.mp hmul) with hpos | hneg
  · have hkone : k = 1 := hpos.1
    subst k
    exact congrArg zpowers (by simpa only [zpow_one] using hk)
  · have hkneg : k = -1 := hneg.1
    subst k
    have hga : g = a⁻¹ := by simpa only [zpow_neg_one] using hk.symm
    rw [hga]
    simp

end Subgroup

namespace FreeGroup

variable {X : Type*} [DecidableEq X]

/-- Exponent-sum detector for one displayed free generator. -/
def generatorExponent (x : X) : FreeGroup X →* Multiplicative ℤ :=
  FreeGroup.lift fun y ↦ if y = x then Multiplicative.ofAdd 1 else 1

@[simp]
theorem generatorExponent_of (x : X) :
    generatorExponent x (FreeGroup.of x) = Multiplicative.ofAdd 1 := by
  simp [generatorExponent]

/-- A cyclic subgroup of a free group containing a displayed free generator is exactly the
subgroup generated by that generator. -/
theorem zpowers_eq_of_generator_mem (x : X) (a : FreeGroup X)
    (hmem : FreeGroup.of x ∈ Subgroup.zpowers a) :
    Subgroup.zpowers a = Subgroup.zpowers (FreeGroup.of x) :=
  Subgroup.zpowers_eq_of_mem_of_multiplicativeInt_detector
    (FreeGroup.of x) a (generatorExponent x) (generatorExponent_of x) hmem

end FreeGroup
