/-
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/

import Mathlib

/-!
# Square-zero exchange flows

This file exports the proof-independent content of V10 Lemma 6.1. A square-zero endomorphism
generates an additive one-parameter family of linear equivalences, and an infinitesimally
invariant bilinear form is invariant under the whole family.
-/

namespace Lib.LinearAlgebra.SquareZeroExchange

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The linear exchange `1 + sN` generated by an endomorphism `N`. -/
def exchange (N : Module.End R M) (s : R) : Module.End R M :=
  1 + s • N

@[simp]
theorem exchange_zero (N : Module.End R M) : exchange N 0 = 1 := by
  simp [exchange]

@[simp]
theorem exchange_apply (N : Module.End R M) (s : R) (x : M) :
    exchange N s x = x + s • N x := by
  simp [exchange]

/-- Square-zero exchanges compose by adding their parameters. -/
theorem exchange_mul_exchange {N : Module.End R M} (hN : N * N = 0) (s t : R) :
    exchange N s * exchange N t = exchange N (s + t) := by
  ext x
  have hNN : N (N x) = 0 := by
    simpa [Module.End.mul_apply] using DFunLike.congr_fun hN x
  simp only [Module.End.mul_apply, exchange_apply, map_add, map_smul, hNN, smul_zero, add_zero]
  module

/-- A square-zero exchange as a linear equivalence. -/
def exchangeEquiv (N : Module.End R M) (hN : N * N = 0) (s : R) : M ≃ₗ[R] M :=
  LinearEquiv.ofLinearMap (exchange N s) (exchange N (-s))
    (by
      rw [← Module.End.mul_eq_comp, exchange_mul_exchange hN, add_neg_cancel, exchange_zero]
      rfl)
    (by
      rw [← Module.End.mul_eq_comp, exchange_mul_exchange hN, neg_add_cancel, exchange_zero]
      rfl)

@[simp]
theorem exchangeEquiv_toLinearMap {N : Module.End R M} (hN : N * N = 0) (s : R) :
    (exchangeEquiv N hN s).toLinearMap = exchange N s :=
  rfl

@[simp]
theorem exchangeEquiv_apply {N : Module.End R M} (hN : N * N = 0) (s : R) (x : M) :
    exchangeEquiv N hN s x = exchange N s x :=
  rfl

/-- The inverse of `E_s` is `E_{-s}`. -/
theorem exchangeEquiv_symm_toLinearMap {N : Module.End R M} (hN : N * N = 0) (s : R) :
    (exchangeEquiv N hN s).symm.toLinearMap = exchange N (-s) :=
  rfl

/-- The quadratic term forced by a square-zero skew operator vanishes. -/
theorem quadratic_term_eq_zero {N : Module.End R M} (hN : N * N = 0)
    (Q : LinearMap.BilinForm R M)
    (hskew : ∀ x y, Q (N x) y + Q x (N y) = 0) (x y : M) :
    Q (N x) (N y) = 0 := by
  have hNN : N (N y) = 0 := by
    simpa [Module.End.mul_apply] using DFunLike.congr_fun hN y
  simpa [hNN] using hskew x (N y)

/-- An infinitesimally invariant bilinear form is preserved by every square-zero exchange. -/
theorem exchange_preserves_bilin {N : Module.End R M} (hN : N * N = 0)
    (Q : LinearMap.BilinForm R M)
    (hskew : ∀ x y, Q (N x) y + Q x (N y) = 0) (s : R) (x y : M) :
    Q (exchange N s x) (exchange N s y) = Q x y := by
  have hquad := quadratic_term_eq_zero hN Q hskew x y
  simp only [exchange_apply, map_add, map_smul, LinearMap.add_apply, LinearMap.smul_apply,
    smul_eq_mul]
  linear_combination s * hskew x y + s ^ 2 * hquad

/-- The bilinear conservation theorem stated using Mathlib's skew-adjoint predicate. -/
theorem exchange_preserves_bilin_of_isSkewAdjoint {N : Module.End R M} (hN : N * N = 0)
    (Q : LinearMap.BilinForm R M) (hskew : Q.IsSkewAdjoint N) (s : R) (x y : M) :
    Q (exchange N s x) (exchange N s y) = Q x y := by
  apply exchange_preserves_bilin hN Q
  intro u v
  rw [hskew u v]
  simp

end Lib.LinearAlgebra.SquareZeroExchange
