/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Mathlib.GroupTheory.FreeGroup.Basic
public import Mathlib.RepresentationTheory.Coinvariants

/-!
# Coinvariants of free-group representations

For a linear representation `ρ` of a free group `F(A)` on a module `V`, the submodule of
coinvariant relations is generated by the differences `ρ (x_a) v - v` for the distinguished free
generators `x_a` alone: the coinvariants are `V / ⟨(x_a - 1) v⟩`.  Arbitrary words impose no
further relations.

## Main results

* `Representation.coinvariants_ker_eq_freeGroupGeneratorRelations`: the generator differences span
  `Representation.Coinvariants.ker`.

## References

* [Kenneth S. Brown, *Cohomology of Groups*][brown1982], II.2 (coinvariants presented by a set of
  generators) and III.1 (homology with coefficients, `H₀(G; M) = M_G`).
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false

namespace Representation

universe u v w

variable {R : Type u} {A : Type v} {V : Type w}
variable [CommRing R] [AddCommGroup V] [Module R V]

/-- The relation submodule generated by the distinguished generators of a free-group
representation. -/
def freeGroupGeneratorRelations (ρ : Representation R (FreeGroup A) V) : Submodule R V :=
  Submodule.span R (Set.range fun ax : A × V ↦ ρ (FreeGroup.of ax.1) ax.2 - ax.2)

/-- For a free-group representation, the distinguished-generator relations generate all
coinvariant relations. -/
theorem coinvariants_ker_eq_freeGroupGeneratorRelations
    (ρ : Representation R (FreeGroup A) V) :
    Coinvariants.ker ρ = freeGroupGeneratorRelations ρ := by
  apply le_antisymm
  · rw [Coinvariants.ker]
    apply Submodule.span_le.2
    rintro y ⟨⟨g, x⟩, rfl⟩
    revert x
    refine FreeGroup.induction_on g ?_ ?_ ?_ ?_
    · intro x
      simp
    · intro a x
      exact Submodule.subset_span (Set.mem_range_self (a, x))
    · intro a ha x
      have h := ha (ρ (FreeGroup.of a)⁻¹ x)
      have hn := (freeGroupGeneratorRelations ρ).neg_mem h
      simpa [map_inv, sub_eq_add_neg, add_comm] using hn
    · intro g h hg hh x
      have hm := (freeGroupGeneratorRelations ρ).add_mem
        (hg (ρ h x)) (hh x)
      simpa [map_mul] using hm
  · apply Submodule.span_le.2
    rintro y ⟨⟨a, x⟩, rfl⟩
    exact Coinvariants.sub_mem_ker (FreeGroup.of a) x

end Representation
