/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Lib.Algebra.Homology.SpectralObject.TotalFiltration
public import Mathlib.Algebra.Homology.ShortComplex.Ab
public import Mathlib.Algebra.Homology.SpectralObject.Page
public import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# The stable endpoint of an abelian spectral object

For an additive-group-valued spectral object indexed by the extended integers, this file defines
the stable endpoint at filtration degree `q` as

`E^n(⊥ → q, q → q+1, q+1 → ⊤)`.

It then identifies this object with the successive quotient of the canonical total filtration.
The proof uses the exact sequences of the spectral object itself: the map from `[⊥,q+1]` to the
stable endpoint has kernel generated by the images of `[⊥,q]` and `[q+1,⊤]`, while the latter
image is exactly the kernel of the map from `[⊥,q+1]` to `[⊥,⊤]`.

No quadrant, boundedness, page-stabilization, or external convergence hypothesis is required.
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.ComposableArrows

namespace CategoryTheory.Abelian.SpectralObject

variable (X : SpectralObject AddCommGrpCat EInt) (n q : ℤ)

/-- The stable endpoint subquotient of a spectral object in total degree `n` at filtration
degree `q`. -/
def stableE : AddCommGrpCat :=
  X.E
    (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
    (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
    (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
    (n - 1) n (n + 1)

/-- The quotient projection from the interval `[⊥,q+1]` to the stable endpoint. -/
def stableEProjection :
    (X.H n).obj
        (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))) ⟶
      X.stableE n q :=
  X.toCycles
      (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
      (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
      (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
      (Subsingleton.elim _ _) n ≫
    X.πE
      (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
      (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
      (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
      (n - 1) n (n + 1)

/-- The canonical projection from a filtration level to the stable endpoint. -/
def totalFiltrationToStableE :
    X.totalFiltration n ((q + 1 : ℤ) : EInt) →+ X.stableE n q :=
  (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.rangeRestrict.liftOfSurjective
    (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.rangeRestrict_surjective
    ⟨(X.stableEProjection n q).hom, by
      intro x hx
      have hx₁ : x ∈ (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.ker := by
        rwa [← AddMonoidHom.ker_rangeRestrict]
      have hx₂ :
          ((X.H n).map (twoδ₂Toδ₁
            (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
            (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
            (homOfLE (bot_le : (⊥ : EInt) ≤ ⊤)) (Subsingleton.elim _ _))).hom x = 0 := by
        change (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom x = 0
        exact AddMonoidHom.mem_ker.mp hx₁
      have hex := (CategoryTheory.ShortComplex.ab_exact_iff_function_exact
        (X.sc₁
          (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
          (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
          (homOfLE (bot_le : (⊥ : EInt) ≤ ⊤)) (Subsingleton.elim _ _)
          (n - 1) n)).mp
        (X.exact₁
          (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
          (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
          (homOfLE (bot_le : (⊥ : EInt) ≤ ⊤)) (Subsingleton.elim _ _)
          (n - 1) n)
      have hx' := (hex x).mp (by
        simpa [SpectralObject.sc₁] using hx₂)
      obtain ⟨y, hy⟩ := hx'
      have hy' :
          (X.δ
            (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
            (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
            (n - 1) n).hom y = x := by
        simpa [SpectralObject.sc₁] using hy
      apply AddMonoidHom.mem_ker.mpr
      rw [← hy']
      unfold stableEProjection stableE
      change
        (X.δ
          (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
          (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤)) (n - 1) n ≫
        X.toCycles
          (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
          (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
          (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
          (Subsingleton.elim _ _) n ≫
        X.πE
          (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
          (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
          (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
          (n - 1) n (n + 1)).hom y = 0
      rw [← Category.assoc,
        X.δ_toCycles
          (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
          (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
          (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
          (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
          (Subsingleton.elim _ _) (n - 1) n (by omega),
        X.δToCycles_πE
          (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
          (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
          (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
          (n - 1) n (n + 1) (by omega) (by omega)]
      rfl⟩

/-- The filtration-level projection is induced by `stableEProjection`. -/
@[simp]
lemma totalFiltrationToStableE_rangeRestrict (x) :
    X.totalFiltrationToStableE n q
        ((X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.rangeRestrict x) =
      (X.stableEProjection n q).hom x := by
  unfold totalFiltrationToStableE
  apply AddMonoidHom.liftOfRightInverse_comp_apply

/-- The canonical projection from a filtration level to the stable endpoint is surjective. -/
lemma totalFiltrationToStableE_surjective :
    Function.Surjective (X.totalFiltrationToStableE n q) := by
  intro z
  have hp : Function.Surjective (X.stableEProjection n q) := by
    apply (AddCommGrpCat.epi_iff_surjective _).mp
    unfold stableEProjection stableE
    change Epi (X.cokernelSequenceE
      (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
      (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
      (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
      (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
      (Subsingleton.elim _ _) (n - 1) n (n + 1)).g
    infer_instance
  obtain ⟨x, rfl⟩ := hp z
  exact ⟨(X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.rangeRestrict x, by simp⟩

/-- The kernel of the stable-endpoint projection is the preceding filtration level. -/
lemma totalFiltrationToStableE_ker :
    (X.totalFiltrationToStableE n q).ker =
      (X.totalFiltration n (q : EInt)).addSubgroupOf
        (X.totalFiltration n ((q + 1 : ℤ) : EInt)) := by
  let lower :
      (X.H n).obj
          (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))) ⟶
        (X.H n).obj
          (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))) :=
    (X.H n).map (twoδ₂Toδ₁
      (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
      (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
      (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
      (Subsingleton.elim _ _))
  let tail :
      (X.H (n - 1)).obj
          (mk₁ (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))) ⟶
        (X.H n).obj
          (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))) :=
    X.δ
      (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
      (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤)) (n - 1) n
  let sourceToTotal :
      (X.H n).obj
          (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))) ⟶
        (X.H n).obj (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ ⊤))) :=
    (X.H n).map (twoδ₂Toδ₁
      (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
      (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
      (homOfLE (bot_le : (⊥ : EInt) ≤ ⊤)) (Subsingleton.elim _ _))
  have hlower : lower = X.totalFiltrationTransition n
      (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp) := by
    dsimp [lower, totalFiltrationTransition]
    congr 1
  have htotal : sourceToTotal =
      X.totalFiltrationMap n ((q + 1 : ℤ) : EInt) := by
    dsimp [sourceToTotal, totalFiltrationMap]
    congr 1
  have hlowerProjection : lower ≫ X.stableEProjection n q = 0 := by
    dsimp [lower]
    unfold stableEProjection stableE
    rw [← Category.assoc, X.H_map_twoδ₂Toδ₁_toCycles, zero_comp]
  have htailTotal : tail ≫ sourceToTotal = 0 := by
    exact (X.sc₁
      (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
      (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
      (homOfLE (bot_le : (⊥ : EInt) ≤ ⊤)) (Subsingleton.elim _ _)
      (n - 1) n).zero
  have hcombined : biprod.desc lower tail ≫ sourceToTotal =
      biprod.fst ≫ X.totalFiltrationMap n (q : EInt) := by
    apply biprod.hom_ext'
    · rw [biprod.inl_desc_assoc, biprod.inl_fst_assoc, hlower, htotal,
        X.totalFiltrationTransition_comp]
    · rw [biprod.inr_desc_assoc, biprod.inr_fst_assoc, htailTotal, zero_comp]
  have hex (x) (hx : (X.stableEProjection n q).hom x = 0) :
      ∃ y, (biprod.desc lower tail).hom y = x := by
    have h := (CategoryTheory.ShortComplex.ab_exact_iff_function_exact
      (X.cokernelSequenceE
        (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
        (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
        (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
        (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
        (Subsingleton.elim _ _) (n - 1) n (n + 1))).mp
      (X.cokernelSequenceE_exact
        (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))
        (homOfLE (show (q : EInt) ≤ ((q + 1 : ℤ) : EInt) by simp))
        (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤))
        (homOfLE (bot_le : (⊥ : EInt) ≤ ((q + 1 : ℤ) : EInt)))
        (Subsingleton.elim _ _) (n - 1) n (n + 1))
    have hx' := (h x).mp (by
      simpa [stableEProjection, stableE, SpectralObject.cokernelSequenceE,
        ConcreteCategory.comp_apply] using hx)
    obtain ⟨y, hy⟩ := hx'
    exact ⟨y, by
      simpa [lower, tail, SpectralObject.cokernelSequenceE] using hy⟩
  ext z
  rw [AddSubgroup.mem_addSubgroupOf]
  constructor
  · intro hz
    rw [AddMonoidHom.mem_ker] at hz
    obtain ⟨x, hx⟩ :=
      (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.rangeRestrict_surjective z
    have hxg : (X.stableEProjection n q).hom x = 0 := by
      rw [← totalFiltrationToStableE_rangeRestrict X n q x, hx]
      exact hz
    obtain ⟨y, hy⟩ := hex x hxg
    refine ⟨((biprod.fst :
      ((X.H n).obj
          (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))) ⊞
        (X.H (n - 1)).obj
          (mk₁ (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤)))) ⟶
        (X.H n).obj
          (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt))))).hom y), ?_⟩
    rw [← hx]
    change (X.totalFiltrationMap n (q : EInt)).hom
      ((biprod.fst :
        ((X.H n).obj
            (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt)))) ⊞
          (X.H (n - 1)).obj
            (mk₁ (homOfLE (le_top : ((q + 1 : ℤ) : EInt) ≤ ⊤)))) ⟶
          (X.H n).obj
            (mk₁ (homOfLE (bot_le : (⊥ : EInt) ≤ (q : EInt))))).hom y) =
      (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom x
    rw [← htotal, ← hy]
    simpa only [ConcreteCategory.comp_apply] using
      congrArg (fun k => k.hom y) hcombined.symm
  · rintro ⟨x, hx⟩
    rw [AddMonoidHom.mem_ker]
    let hq : (q : EInt) ≤ ((q + 1 : ℤ) : EInt) := by simp
    have heq : z =
        (X.totalFiltrationMap n ((q + 1 : ℤ) : EInt)).hom.rangeRestrict
          (lower.hom x) := by
      apply Subtype.ext
      rw [AddMonoidHom.coe_rangeRestrict, hlower]
      simpa only [ConcreteCategory.comp_apply, hx] using
        congrArg (fun k => k.hom x) (X.totalFiltrationTransition_comp n hq).symm
    rw [heq, totalFiltrationToStableE_rangeRestrict]
    simpa using congrArg (fun k => k.hom x) hlowerProjection

/-- The successive quotient of the total filtration is the stable endpoint subquotient. -/
def totalFiltrationGradedEquiv :
    X.totalFiltration n ((q + 1 : ℤ) : EInt) ⧸
        (X.totalFiltration n (q : EInt)).addSubgroupOf
          (X.totalFiltration n ((q + 1 : ℤ) : EInt)) ≃+
      X.stableE n q :=
  (QuotientAddGroup.quotientAddEquivOfEq
      (X.totalFiltrationToStableE_ker n q).symm).trans
    (QuotientAddGroup.quotientKerEquivOfSurjective
      (X.totalFiltrationToStableE n q)
      (X.totalFiltrationToStableE_surjective n q))

/-- On quotient representatives, `totalFiltrationGradedEquiv` is the canonical stable-endpoint
projection. -/
@[simp]
lemma totalFiltrationGradedEquiv_mk
    (x : X.totalFiltration n ((q + 1 : ℤ) : EInt)) :
    X.totalFiltrationGradedEquiv n q (QuotientAddGroup.mk x) =
      X.totalFiltrationToStableE n q x := by
  rfl

end CategoryTheory.Abelian.SpectralObject
