/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Lib.Topology.Sheaves.PrincipalCoverLocalSystem
import Mathlib.GroupTheory.GroupAction.FixedPoints
public import Mathlib.Topology.Connected.LocallyPathConnected
public import Mathlib.Topology.Homotopy.Lifting

/-!
# Sections over an open with cyclic covering components

Let an open subset of the base of a principal `G`-cover have one distinguished connected
component upstairs.  Suppose all components are deck translates of it and its stabilizer is the
cyclic subgroup generated by `a : G`.  Evaluation on that component identifies equivariant
locally constant sections with coefficients fixed by `a`.

This is the section-theoretic half of the standard punctured-disc computation for a local
system.  The geometric input is deliberately isolated in `CyclicComponentData`; in particular,
this file makes no claim about any specific family or derived direct image.
-/

@[expose] public section

noncomputable section

open Set TopologicalSpace Topology

namespace PrincipalCoverLocalSystem

universe uG u

variable {G : Type uG} {E X M : Type u}
  [Group G] [TopologicalSpace E] [TopologicalSpace X]
  [MulAction G E] [AddCommGroup M] [DistribMulAction G M]

/-- Deck translation on a lifted open, as a homeomorphism. -/
def liftedActionHomeomorph (p : E → X) (hp : IsQuotientCoveringMap p G)
    (U : Opens X) (g : G) : LiftedOpen p U ≃ₜ LiftedOpen p U where
  toFun := liftedAction p hp U g
  invFun := liftedAction p hp U g⁻¹
  left_inv z := by
    apply Subtype.ext
    simp [liftedAction]
  right_inv z := by
    apply Subtype.ext
    simp [liftedAction]
  continuous_toFun :=
    (hp.continuous_const_smul g).comp continuous_subtype_val |>.subtype_mk _
  continuous_invFun :=
    (hp.continuous_const_smul g⁻¹).comp continuous_subtype_val |>.subtype_mk _

@[simp]
theorem liftedActionHomeomorph_apply (p : E → X) (hp : IsQuotientCoveringMap p G)
    (U : Opens X) (g : G) (z : LiftedOpen p U) :
    liftedActionHomeomorph p hp U g z = liftedAction p hp U g z :=
  rfl

/-! ## Connected components and local deck monodromy -/

/-- The base point in an open under a chosen point of its lifted inverse image. -/
def liftedOpenBase {p : E → X} {U : Opens X} (base : LiftedOpen p U) : U :=
  ⟨p base.1, base.2⟩

/-- A chosen point of a lifted open, regarded as a point in the corresponding ambient fibre. -/
def liftedOpenAmbientFiber {p : E → X} {U : Opens X} (base : LiftedOpen p U) :
    p ⁻¹' {p base.1} :=
  ⟨base.1, rfl⟩

/-- Inclusion of an open subspace into its ambient space. -/
def openInclusion (U : Opens X) : C(U, X) :=
  ⟨Subtype.val, continuous_subtype_val⟩

/-- Local deck monodromy on an open, normalized with the same inversion convention as the
free-word homomorphism of a principal cover. -/
def localDeckMonodromyHom {p : E → X} (hp : IsQuotientCoveringMap p G)
    {U : Opens X} (base : LiftedOpen p U) :
    FundamentalGroup U (liftedOpenBase base) →* G :=
  (MulEquiv.inv' G).symm.toMonoidHom.comp
    ((hp.fundamentalGroupToMulOpposite (liftedOpenAmbientFiber base)).comp
      (FundamentalGroup.map (openInclusion U) (liftedOpenBase base)))

/-- A deck translate of a lifted base point lies in its connected component exactly when the
inverse deck element occurs as local monodromy.  Thus a concrete component-stabilizer calculation
reduces to the image of the fundamental group of the open in the ambient deck group. -/
theorem liftedAction_mem_connectedComponent_iff_inv_mem_localDeckMonodromy_range
    {p : E → X} (hp : IsQuotientCoveringMap p G) {U : Opens X}
    [LocallyPathConnectedSpace (LiftedOpen p U)]
    (base : LiftedOpen p U) (g : G) :
    liftedAction p hp U g base ∈ connectedComponent base ↔
      g⁻¹ ∈ (localDeckMonodromyHom hp base).range := by
  rw [← pathComponent_eq_connectedComponent base, mem_pathComponent_iff]
  constructor
  · rintro ⟨Γ⟩
    let δ : Path (liftedOpenBase base) (liftedOpenBase base) :=
      { toFun := fun t => ⟨p (Γ t).1, (Γ t).2⟩
        continuous_toFun :=
          (hp.continuous.comp (continuous_subtype_val.comp Γ.continuous)).subtype_mk _
        source' := Subtype.ext (congrArg (fun z : LiftedOpen p U => p z.1) Γ.source)
        target' := Subtype.ext <| by
          change p (Γ 1).1 = p base.1
          have h := congrArg (fun z : LiftedOpen p U => p z.1) Γ.target
          simpa only [liftedAction, hp.map_smul] using h }
    let γU : FundamentalGroup U (liftedOpenBase base) :=
      FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk δ)
    refine ⟨γU, ?_⟩
    change
      (MulEquiv.inv' G).symm
          (hp.fundamentalGroupToMulOpposite (liftedOpenAmbientFiber base)
            (FundamentalGroup.map (openInclusion U) (liftedOpenBase base) γU)) =
        g⁻¹
    apply (MulEquiv.inv' G).injective
    simp only [MulEquiv.apply_symm_apply, MulEquiv.inv'_apply, Function.comp_apply, inv_inv]
    apply hp.fundamentalGroupToMulOpposite_apply_eq_Iff.mpr
    change g • base.1 = _
    have hmon :
        hp.isCoveringMap.monodromy
            (FundamentalGroup.map (openInclusion U) (liftedOpenBase base) γU)
            (liftedOpenAmbientFiber base) =
          ⟨g • base.1, hp.map_smul g⟩ := by
      apply hp.isCoveringMap.monodromy_eq_of_map_eq
        (Path.Homotopic.Quotient.mk (Γ.map continuous_subtype_val))
      apply congrArg Path.Homotopic.Quotient.mk
      ext t
      rfl
    exact congrArg Subtype.val hmon |>.symm
  · rintro ⟨γU, hγU⟩
    induction γU using Path.Homotopic.Quotient.ind with
    | mk δ =>
      let δX : Path (p base.1) (p base.1) :=
        δ.map continuous_subtype_val
      have hδzero : δX 0 = p base.1 := δX.source
      let Γ : C(unitInterval, E) := hp.isCoveringMap.liftPath δX base.1 hδzero
      have hΓproj : p ∘ Γ = δX :=
        hp.isCoveringMap.liftPath_lifts δX base.1 hδzero
      have hΓzero : Γ 0 = base.1 :=
        hp.isCoveringMap.liftPath_zero δX base.1 hδzero
      have hmon :
          hp.isCoveringMap.monodromy
              (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk δX))
              (liftedOpenAmbientFiber base) =
            ⟨Γ 1, by
              change p (Γ 1) = p base.1
              calc
                p (Γ 1) = δX 1 := by
                  simpa only [Function.comp_apply] using congrFun hΓproj 1
                _ = p base.1 := δX.target⟩ := by
        apply Subtype.ext
        rfl
      have hdeck :
          hp.fundamentalGroupToMulOpposite (liftedOpenAmbientFiber base)
              (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk δX)) =
            MulOpposite.op g := by
        change
          (MulEquiv.inv' G).symm
              (hp.fundamentalGroupToMulOpposite (liftedOpenAmbientFiber base)
                (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk δX))) =
            g⁻¹ at hγU
        have hh := congrArg (MulEquiv.inv' G) hγU
        simpa only [MulEquiv.apply_symm_apply, MulEquiv.inv'_apply, Function.comp_apply,
          inv_inv] using hh
      have hendpoint : Γ 1 = g • base.1 := by
        have happly := hp.fundamentalGroupToMulOpposite_apply_eq_Iff.mp hdeck
        rw [hmon] at happly
        simpa only [MulOpposite.unop_op, liftedOpenAmbientFiber] using happly.symm
      have hΓmem (t : unitInterval) : p (Γ t) ∈ U := by
        have h : p (Γ t) = (δ t).1 := by
          calc
            p (Γ t) = δX t := by
              simpa only [Function.comp_apply] using congrFun hΓproj t
            _ = (δ t).1 := rfl
        rw [h]
        exact (δ t).2
      let ΓU : Path base (liftedAction p hp U g base) :=
        { toFun := fun t => ⟨Γ t, hΓmem t⟩
          continuous_toFun := Γ.continuous.subtype_mk hΓmem
          source' := Subtype.ext hΓzero
          target' := Subtype.ext hendpoint }
      exact ⟨ΓU⟩

/-- The geometric information needed to compute sections over an open whose lifted covering has
cyclic component stabilizer. -/
structure CyclicComponentData (p : E → X) (hp : IsQuotientCoveringMap p G)
    (U : Opens X) (a : G) where
  /-- A distinguished component of the lifted open. -/
  component : Set (LiftedOpen p U)
  /-- A point at which sections are evaluated. -/
  base : LiftedOpen p U
  base_mem : base ∈ component
  component_isOpen : IsOpen component
  component_isPreconnected : IsPreconnected component
  /-- Every lifted point lies in a deck translate of the distinguished component. -/
  translates_cover : ∀ z : LiftedOpen p U,
    ∃ (g : G) (c : LiftedOpen p U), c ∈ component ∧ z = liftedAction p hp U g c
  /-- The generator preserves the distinguished component. -/
  generator_base_mem : liftedAction p hp U a base ∈ component
  /-- Any deck transformation carrying one point of the component back into it is a power of the
  displayed generator. -/
  overlap_cyclic : ∀ (g : G) (c d : LiftedOpen p U),
    c ∈ component → d ∈ component → liftedAction p hp U g c = d →
      ∃ k : ℤ, g = a ^ k

namespace CyclicComponentData

variable {p : E → X} {hp : IsQuotientCoveringMap p G} {U : Opens X} {a : G}

/-- Over a path-connected open, deck translates of any chosen connected component cover the
entire lifted open. -/
theorem exists_translate_mem_connectedComponent
    (hpath : PathConnectedSpace U) (base z : LiftedOpen p U) :
    ∃ g : G, liftedAction p hp U g z ∈ connectedComponent base := by
  let _ := hpath
  let x₀ : U := ⟨p base.1, base.2⟩
  let x₁ : U := ⟨p z.1, z.2⟩
  let γU : Path x₀ x₁ := (PathConnectedSpace.joined x₀ x₁).somePath
  let γX : Path (p base.1) (p z.1) := γU.map continuous_subtype_val
  have hγ₀ : γX 0 = p base.1 := γX.source
  let Γ : C(unitInterval, E) := hp.isCoveringMap.liftPath γX base.1 hγ₀
  have hΓ : p ∘ Γ = γX := hp.isCoveringMap.liftPath_lifts γX base.1 hγ₀
  have hΓ₀ : Γ 0 = base.1 := hp.isCoveringMap.liftPath_zero γX base.1 hγ₀
  let c : LiftedOpen p U := ⟨Γ 1, by
    have h : p (Γ 1) = p z.1 := by
      calc
        p (Γ 1) = γX 1 := by simpa only [Function.comp_apply] using congrFun hΓ 1
        _ = p z.1 := γX.target
    rw [h]
    exact z.2⟩
  have hΓmem (t : unitInterval) : p (Γ t) ∈ U := by
    have h : p (Γ t) = (γU t).1 := by
      calc
        p (Γ t) = γX t := by simpa only [Function.comp_apply] using congrFun hΓ t
        _ = (γU t).1 := rfl
    rw [h]
    exact (γU t).2
  let ΓU : Path base c :=
    {
    toFun t := ⟨Γ t, hΓmem t⟩
    continuous_toFun := Γ.continuous.subtype_mk hΓmem
    source' := Subtype.ext hΓ₀
    target' := rfl }
  have hc : c ∈ connectedComponent base :=
    pathComponent_subset_component base (show Joined base c from ⟨ΓU⟩)
  have hpcz : p c.1 = p z.1 := by
    change p (Γ 1) = p z.1
    calc
      p (Γ 1) = γX 1 := by simpa only [Function.comp_apply] using congrFun hΓ 1
      _ = p z.1 := γX.target
  obtain ⟨g, hg⟩ := hp.apply_eq_iff_mem_orbit.mp hpcz
  refine ⟨g, ?_⟩
  have heq : liftedAction p hp U g z = c := Subtype.ext hg
  exact heq.symm ▸ hc

/-- Build the geometric data from one connected component, transitivity of deck translates, and
the stabilizer calculation at its base point.  The non-base-point overlap condition then follows
formally by translating connected sets. -/
def ofConnectedComponent [LocallyConnectedSpace (LiftedOpen p U)]
    (base : LiftedOpen p U)
    (htranslates : ∀ z : LiftedOpen p U,
      ∃ g : G, liftedAction p hp U g z ∈ connectedComponent base)
    (hstabilizer : ∀ g : G,
      liftedAction p hp U g base ∈ connectedComponent base ↔
        ∃ k : ℤ, g = a ^ k) :
    CyclicComponentData p hp U a where
  component := connectedComponent base
  base := base
  base_mem := mem_connectedComponent
  component_isOpen := isOpen_connectedComponent
  component_isPreconnected := isPreconnected_connectedComponent
  translates_cover z := by
    obtain ⟨g, hg⟩ := htranslates z
    refine ⟨g⁻¹, liftedAction p hp U g z, hg, ?_⟩
    apply Subtype.ext
    simp [liftedAction]
  generator_base_mem := (hstabilizer a).mpr ⟨1, by simp⟩
  overlap_cyclic g c d hc hd hcd := by
    let T := liftedActionHomeomorph p hp U g
    let C := connectedComponent base
    have himg : IsPreconnected (T '' C) :=
      isPreconnected_connectedComponent.image T T.continuous.continuousOn
    have hdimg : d ∈ T '' C := by
      exact ⟨c, hc, by simpa only [T, liftedActionHomeomorph_apply] using hcd⟩
    have hgbase : T base ∈ T '' C := ⟨base, mem_connectedComponent, rfl⟩
    have hunion : IsPreconnected ((T '' C) ∪ C) :=
      himg.union d hdimg hd isPreconnected_connectedComponent
    have hsubset : (T '' C) ∪ C ⊆ connectedComponent base :=
      hunion.subset_connectedComponent (Set.mem_union_right _ mem_connectedComponent)
    apply (hstabilizer g).mp
    exact hsubset (Set.mem_union_left _ hgbase)

/-- Convenient form of `ofConnectedComponent`: path connectedness of the base open supplies
transitivity of component translates automatically, so only the local stabilizer computation
remains as geometric input. -/
def ofPathConnectedComponentStabilizer [LocallyConnectedSpace (LiftedOpen p U)]
    (hpath : PathConnectedSpace U) (base : LiftedOpen p U)
    (hstabilizer : ∀ g : G,
      liftedAction p hp U g base ∈ connectedComponent base ↔
        ∃ k : ℤ, g = a ^ k) :
    CyclicComponentData p hp U a :=
  ofConnectedComponent base
    (fun z ↦ exists_translate_mem_connectedComponent hpath base z) hstabilizer

noncomputable def chosenGroup (D : CyclicComponentData p hp U a)
    (z : LiftedOpen p U) : G :=
  (D.translates_cover z).choose

noncomputable def chosenPoint (D : CyclicComponentData p hp U a)
    (z : LiftedOpen p U) : LiftedOpen p U :=
  (D.translates_cover z).choose_spec.choose

theorem chosenPoint_mem (D : CyclicComponentData p hp U a)
    (z : LiftedOpen p U) : D.chosenPoint z ∈ D.component :=
  (D.translates_cover z).choose_spec.choose_spec.1

theorem chosen_representation (D : CyclicComponentData p hp U a)
    (z : LiftedOpen p U) :
    z = liftedAction p hp U (D.chosenGroup z) (D.chosenPoint z) :=
  (D.translates_cover z).choose_spec.choose_spec.2

theorem zpow_smul_eq (m : M) (ha : a • m = m) (k : ℤ) : a ^ k • m = m := by
  exact MulAction.mem_fixedBy_zpow (show m ∈ MulAction.fixedBy M a from ha) k

theorem chosenGroup_smul_eq_of_representation
    (D : CyclicComponentData p hp U a) (m : M) (ha : a • m = m)
    (z c : LiftedOpen p U) (g : G) (hc : c ∈ D.component)
    (hz : z = liftedAction p hp U g c) :
    D.chosenGroup z • m = g • m := by
  let h := D.chosenGroup z
  let d := D.chosenPoint z
  have hd : d ∈ D.component := D.chosenPoint_mem z
  have hrep : z = liftedAction p hp U h d := D.chosen_representation z
  have heq : liftedAction p hp U (h⁻¹ * g) c = d := by
    apply Subtype.ext
    have hzval := congrArg Subtype.val (hz.symm.trans hrep)
    change g • c.1 = h • d.1 at hzval
    simpa [liftedAction, mul_smul] using congrArg (fun x : E ↦ h⁻¹ • x) hzval
  obtain ⟨k, hk⟩ := D.overlap_cyclic (h⁻¹ * g) c d hc hd heq
  have hfix : (h⁻¹ * g) • m = m := by
    rw [hk]
    exact zpow_smul_eq m ha k
  change h • m = g • m
  calc
    h • m = h • ((h⁻¹ * g) • m) := congrArg (h • ·) hfix.symm
    _ = g • m := by rw [← mul_smul]; simp

def reconstructedValue (D : CyclicComponentData p hp U a)
    (m : M) : LiftedOpen p U → M := fun z ↦ D.chosenGroup z • m

theorem reconstructedValue_of_representation
    (D : CyclicComponentData p hp U a) (m : M) (ha : a • m = m)
    (z c : LiftedOpen p U) (g : G) (hc : c ∈ D.component)
    (hz : z = liftedAction p hp U g c) :
    D.reconstructedValue m z = g • m :=
  D.chosenGroup_smul_eq_of_representation m ha z c g hc hz

theorem reconstructedValue_isLocallyConstant
    (D : CyclicComponentData p hp U a) (m : M) (ha : a • m = m) :
    IsLocallyConstant (D.reconstructedValue m) := by
  rw [IsLocallyConstant.iff_isOpen_fiber]
  intro y
  have hfiber :
      D.reconstructedValue m ⁻¹' {y} =
        ⋃ g : {g : G // g • m = y},
          liftedActionHomeomorph p hp U g.1 '' D.component := by
    ext z
    constructor
    · intro hzS
      obtain ⟨g, c, hc, hzc⟩ := D.translates_cover z
      have hvalue : D.reconstructedValue m z = g • m :=
        D.reconstructedValue_of_representation m ha z c g hc hzc
      apply Set.mem_iUnion.mpr
      refine ⟨⟨g, ?_⟩, c, hc, ?_⟩
      · exact hvalue.symm.trans hzS
      simpa only [liftedActionHomeomorph_apply] using hzc.symm
    · intro hz
      obtain ⟨g, c, hc, rfl⟩ := Set.mem_iUnion.mp hz
      have hvalue := D.reconstructedValue_of_representation m ha
        (liftedAction p hp U g.1 c) c g.1 hc rfl
      exact hvalue.trans g.2
  rw [hfiber]
  exact isOpen_iUnion fun g ↦
    (liftedActionHomeomorph p hp U g.1).isOpenMap D.component D.component_isOpen

def reconstructedSection (D : CyclicComponentData p hp U a)
    (m : M) (ha : a • m = m) : equivariantSections (M := M) p hp U :=
  ⟨⟨D.reconstructedValue m, D.reconstructedValue_isLocallyConstant m ha⟩, by
    intro g z
    obtain ⟨h, c, hc, hzc⟩ := D.translates_cover z
    have hzvalue := D.reconstructedValue_of_representation m ha z c h hc hzc
    have hgz : liftedAction p hp U g z = liftedAction p hp U (g * h) c := by
      apply Subtype.ext
      exact congrArg (fun x : E ↦ g • x) (congrArg Subtype.val hzc) |>.trans (mul_smul g h c.1).symm
    change D.reconstructedValue m (liftedAction p hp U g z) =
      g • D.reconstructedValue m z
    rw [D.reconstructedValue_of_representation m ha _ c (g * h) hc hgz,
      hzvalue, mul_smul]⟩

/-- Evaluation on the distinguished component, landing in any displayed copy of the coefficients
whose membership predicate is fixedness by the cyclic generator. -/
def sectionEvaluation (D : CyclicComponentData p hp U a) (N : AddSubgroup M)
    (hN : ∀ m : M, m ∈ N ↔ a • m = m) :
    equivariantSections (M := M) p hp U →+ N where
  toFun s := ⟨s.1 D.base, (hN _).mpr <| by
    rw [← s.2 a D.base]
    exact s.1.apply_eq_of_isPreconnected D.component_isPreconnected
      D.generator_base_mem D.base_mem⟩
  map_zero' := rfl
  map_add' _ _ := rfl

/-- The inverse of component evaluation, obtained by translating a fixed coefficient over all
deck translates of the distinguished component. -/
def sectionReconstruction (D : CyclicComponentData p hp U a) (N : AddSubgroup M)
    (hN : ∀ m : M, m ∈ N ↔ a • m = m) :
    N →+ equivariantSections (M := M) p hp U where
  toFun m := reconstructedSection D m.1 ((hN m.1).mp m.2)
  map_zero' := by
    apply Subtype.ext
    apply LocallyConstant.ext
    intro z
    change reconstructedValue D (0 : M) z = 0
    simp [reconstructedValue]
  map_add' m n := by
    apply Subtype.ext
    apply LocallyConstant.ext
    intro z
    change reconstructedValue D (m.1 + n.1) z =
      reconstructedValue D m.1 z + reconstructedValue D n.1 z
    exact smul_add _ _ _

theorem sectionEvaluation_sectionReconstruction
    (D : CyclicComponentData p hp U a) (N : AddSubgroup M)
    (hN : ∀ m : M, m ∈ N ↔ a • m = m) (m : N) :
    D.sectionEvaluation N hN (D.sectionReconstruction N hN m) = m := by
  apply Subtype.ext
  change reconstructedValue D m.1 D.base = m.1
  simpa using D.reconstructedValue_of_representation m.1 ((hN m.1).mp m.2)
    D.base D.base 1 D.base_mem (by simp [liftedAction])

theorem sectionReconstruction_sectionEvaluation
    (D : CyclicComponentData p hp U a) (N : AddSubgroup M)
    (hN : ∀ m : M, m ∈ N ↔ a • m = m)
    (s : equivariantSections (M := M) p hp U) :
    D.sectionReconstruction N hN (D.sectionEvaluation N hN s) = s := by
  apply Subtype.ext
  apply LocallyConstant.ext
  intro z
  obtain ⟨g, c, hc, hzc⟩ := D.translates_cover z
  have hcomponent : s.1 c = s.1 D.base :=
    s.1.apply_eq_of_isPreconnected D.component_isPreconnected hc D.base_mem
  change reconstructedValue D (s.1 D.base) z = s.1 z
  rw [D.reconstructedValue_of_representation (s.1 D.base)
    ((hN _).mp (D.sectionEvaluation N hN s).2) z c g hc hzc]
  rw [hzc, s.2, hcomponent]

/-- Equivariant sections over a cyclic-component open are canonically equivalent to coefficients
fixed by the component generator. -/
def sectionsEquiv (D : CyclicComponentData p hp U a) (N : AddSubgroup M)
    (hN : ∀ m : M, m ∈ N ↔ a • m = m) :
    equivariantSections (M := M) p hp U ≃+ N where
  toFun := D.sectionEvaluation N hN
  invFun := D.sectionReconstruction N hN
  left_inv := D.sectionReconstruction_sectionEvaluation N hN
  right_inv := D.sectionEvaluation_sectionReconstruction N hN
  map_add' := (D.sectionEvaluation N hN).map_add

theorem sectionEvaluation_bijective
    (D : CyclicComponentData p hp U a) (N : AddSubgroup M)
    (hN : ∀ m : M, m ∈ N ↔ a • m = m) :
    Function.Bijective (D.sectionEvaluation N hN) :=
  (D.sectionsEquiv N hN).bijective

/-- Component evaluation is compatible with restriction whenever the smaller evaluation point
lies in the larger distinguished component.  The statement is independent of the proof of open
containment. -/
theorem sectionEvaluation_restrict
    {V : Opens X} (DV : CyclicComponentData p hp V a)
    (DU : CyclicComponentData p hp U a) (hUV : U ≤ V)
    (N : AddSubgroup M) (hN : ∀ m : M, m ∈ N ↔ a • m = m)
    (hbase : (⟨DU.base.1, hUV DU.base.2⟩ : LiftedOpen p V) ∈ DV.component)
    (s : equivariantSections (M := M) p hp V) :
    DU.sectionEvaluation N hN (restrict (M := M) p hp hUV s) =
      DV.sectionEvaluation N hN s := by
  apply Subtype.ext
  change s.1 ⟨DU.base.1, hUV DU.base.2⟩ = s.1 DV.base
  exact s.1.apply_eq_of_isPreconnected DV.component_isPreconnected hbase DV.base_mem

end CyclicComponentData

end PrincipalCoverLocalSystem
