/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Lib.Topology.Sheaves.FunctionSheaf
public import Lib.Topology.Sheaves.SingularCochainSheaf.Sheaf
public import Mathlib.AlgebraicTopology.SimplicialSet.Homology.Basic
public import Mathlib.AlgebraicTopology.SimplicialSet.TopAdj

/-!
# Degree-zero singular cochains are arbitrary functions

Singular `0`-chains are freely generated by the points of `X`, so a singular `0`-cochain with
values in `A` is the same thing as an arbitrary function `X → A`: `S^0(X; A) = A^X`.  This
identification is compatible with restriction to open subspaces, so the degree-zero
singular-cochain presheaf is the presheaf of all `A`-valued functions (Bredon, *Sheaf Theory*,
III §1; Warner, *Foundations of Differentiable Manifolds and Lie Groups*, 5.31).
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

noncomputable section

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped Simplicial

namespace TopCat.SingularCochainSheaf

/-- The singular simplicial set of a space. -/
abbrev zeroSingularSet (X : Type) [TopologicalSpace X] : SSet :=
  TopCat.toSSet.obj (TopCat.of X)

/-- Singular `n`-chains of `X` with integer coefficients. -/
abbrev NativeChains (X : Type) [TopologicalSpace X] (n : ℕ) :=
  (AlgebraicTopology.SingularCochains.chains X).X n

/-- Singular `n`-cochains of `X` with coefficients in `A`. -/
abbrev NativeCochains (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) (n : ℕ) :=
  NativeChains X n →+ A

/-- The singular `0`-simplex at a point `x`. -/
def pointSimplex (X : Type) [TopologicalSpace X] (x : X) :
    (zeroSingularSet X) _⦋0⦌ :=
  TopCat.toSSetObj₀Equiv.symm x

/-- The point underlying a singular `0`-simplex. -/
def simplexPoint (X : Type) [TopologicalSpace X]
    (σ : (zeroSingularSet X) _⦋0⦌) : X :=
  TopCat.toSSetObj₀Equiv σ

/-- Taking the point of the `0`-simplex at `x` returns `x`. -/
@[simp]
theorem simplexPoint_pointSimplex (X : Type) [TopologicalSpace X] (x : X) :
    simplexPoint X (pointSimplex X x) = x :=
  (TopCat.toSSetObj₀Equiv (X := TopCat.of X)).apply_symm_apply x

/-- Every singular `0`-simplex is the `0`-simplex at its underlying point; points and singular
`0`-simplices correspond. -/
@[simp]
theorem pointSimplex_simplexPoint (X : Type) [TopologicalSpace X]
    (σ : (zeroSingularSet X) _⦋0⦌) : pointSimplex X (simplexPoint X σ) = σ :=
  (TopCat.toSSetObj₀Equiv (X := TopCat.of X)).symm_apply_apply σ

/-- The basis `0`-chain of a singular `0`-simplex. -/
def simplexChain (X : Type) [TopologicalSpace X]
    (σ : (zeroSingularSet X) _⦋0⦌) : NativeChains X 0 :=
  ((zeroSingularSet X).ιChainComplex (R := ModuleCat.of ℤ ℤ) σ).hom 1

/-- Evaluation of a singular `0`-cochain at the points of `X`, giving a function `X → A`. -/
def zeroCochainEvaluate (X : Type) [TopologicalSpace X] (A : AddCommGrpCat.{0}) :
    NativeCochains X A 0 →+ (X → A) where
  toFun c x := c (simplexChain X (pointSimplex X x))
  map_zero' := by funext x; rfl
  map_add' _ _ := by funext x; rfl

/-- The `ℤ`-linear map `ℤ → A`, `n ↦ n • a`. -/
def integerLinear (A : AddCommGrpCat.{0}) (a : A) :
    ModuleCat.of ℤ ℤ ⟶ ModuleCat.of ℤ A :=
  ModuleCat.ofHom
    { toFun := fun n => n • a
      map_add' := fun m n => add_zsmul a m n
      map_smul' := by
        intro m n
        change (m * n) • a = m • n • a
        exact mul_zsmul a m n }

/-- The `ℤ`-linear functional on `0`-chains determined by a function `X → A` on the basis of
`0`-simplices. -/
def functionChainHom (X : Type) [TopologicalSpace X] (A : AddCommGrpCat.{0})
    (f : X → A) : NativeChains X 0 ⟶ ModuleCat.of ℤ A :=
  Sigma.desc (fun σ : (zeroSingularSet X) _⦋0⦌ =>
    integerLinear A (f (simplexPoint X σ)))

/-- The functional determined by `f` evaluates the basis chain of a `0`-simplex by `f` at its
point. -/
@[reassoc (attr := simp)]
theorem iota_functionChainHom (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) (f : X → A) (σ : (zeroSingularSet X) _⦋0⦌) :
    (zeroSingularSet X).ιChainComplex σ ≫ functionChainHom X A f =
      integerLinear A (f (simplexPoint X σ)) := by
  change Sigma.ι _ σ ≫ Sigma.desc _ = _
  simp

/-- The functional determined by the zero function is zero. -/
theorem functionChainHom_zero (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) : functionChainHom X A (0 : X → A) = 0 := by
  apply SSet.chainComplex_hom_ext
  intro σ
  rw [iota_functionChainHom]
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro n
  change n • (0 : A) = 0
  exact zsmul_zero n

/-- The functional determined by a sum of functions is the sum of the functionals. -/
theorem functionChainHom_add (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) (f g : X → A) :
    functionChainHom X A (f + g) = functionChainHom X A f + functionChainHom X A g := by
  apply SSet.chainComplex_hom_ext
  intro σ
  rw [iota_functionChainHom]
  simp only [Preadditive.comp_add, iota_functionChainHom]
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro n
  change n • (f (simplexPoint X σ) + g (simplexPoint X σ)) =
    n • f (simplexPoint X σ) + n • g (simplexPoint X σ)
  exact zsmul_add _ _ n

/-- The singular `0`-cochain determined by an arbitrary function `X → A`. -/
def zeroCochainOfFunction (X : Type) [TopologicalSpace X] (A : AddCommGrpCat.{0}) :
    (X → A) →+ NativeCochains X A 0 where
  toFun f := (functionChainHom X A f).hom.toAddMonoidHom
  map_zero' := by
    apply AddMonoidHom.ext
    intro z
    exact ConcreteCategory.congr_hom (functionChainHom_zero X A) z
  map_add' f g := by
    apply AddMonoidHom.ext
    intro z
    exact ConcreteCategory.congr_hom (functionChainHom_add X A f g) z

/-- Evaluating the cochain determined by `f` returns `f`. -/
@[simp]
theorem zeroCochainEvaluate_ofFunction (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) (f : X → A) :
    zeroCochainEvaluate X A (zeroCochainOfFunction X A f) = f := by
  funext x
  change (functionChainHom X A f).hom
      (((zeroSingularSet X).ιChainComplex (R := ModuleCat.of ℤ ℤ)
        (pointSimplex X x)).hom 1) = f x
  have h := ConcreteCategory.congr_hom
    (iota_functionChainHom X A f (pointSimplex X x)) 1
  calc
    _ = (integerLinear A (f (simplexPoint X (pointSimplex X x)))).hom 1 := h
    _ = f x := by
      rw [simplexPoint_pointSimplex]
      change (1 : ℤ) • f x = f x
      exact one_zsmul (f x)

/-- A `0`-cochain is determined by its values at the points of `X`. -/
theorem zeroCochainOfFunction_evaluate (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) (c : NativeCochains X A 0) :
    zeroCochainOfFunction X A (zeroCochainEvaluate X A c) = c := by
  apply AddMonoidHom.ext
  intro z
  let q : NativeChains X 0 ⟶ ModuleCat.of ℤ A := ModuleCat.ofHom
    { toFun := c
      map_add' := c.map_add
      map_smul' := by
        intro n y
        calc
          c ((NativeChains X 0).isModule.smul n y) = c (n • y) :=
            congrArg c (int_smul_eq_zsmul (NativeChains X 0).isModule n y)
          _ = n • c y := c.map_zsmul n y
          _ = (ModuleCat.of ℤ A).isModule.smul n (c y) :=
            (int_smul_eq_zsmul (ModuleCat.of ℤ A).isModule n (c y)).symm
          _ = (RingHom.id ℤ) n • c y := by rfl }
  have hq : functionChainHom X A (zeroCochainEvaluate X A c) = q := by
    apply SSet.chainComplex_hom_ext
    intro σ
    rw [iota_functionChainHom]
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro n
    change n • c (simplexChain X (pointSimplex X (simplexPoint X σ))) =
      c (((zeroSingularSet X).ιChainComplex (R := ModuleCat.of ℤ ℤ) σ).hom n)
    rw [pointSimplex_simplexPoint]
    have hn : ((zeroSingularSet X).ιChainComplex (R := ModuleCat.of ℤ ℤ) σ).hom n =
        n • simplexChain X σ := by
      simpa [simplexChain] using
        ((zeroSingularSet X).ιChainComplex (R := ModuleCat.of ℤ ℤ)
          σ).hom.toAddMonoidHom.map_zsmul n (1 : ℤ)
    rw [hn, c.map_zsmul]
  exact ConcreteCategory.congr_hom hq z

/-- `S^0(X; A) ≅ A^X`: singular `0`-cochains are exactly the `A`-valued functions on `X`
(Bredon III §1; Warner 5.31). -/
def zeroCochainsIsoFunctions (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) :
    AddCommGrpCat.of (NativeCochains X A 0) ≅ AddCommGrpCat.of (X → A) where
  hom := AddCommGrpCat.ofHom (zeroCochainEvaluate X A)
  inv := AddCommGrpCat.ofHom (zeroCochainOfFunction X A)
  hom_inv_id := by
    apply AddCommGrpCat.hom_ext
    apply AddMonoidHom.ext
    exact zeroCochainOfFunction_evaluate X A
  inv_hom_id := by
    apply AddCommGrpCat.hom_ext
    apply AddMonoidHom.ext
    exact zeroCochainEvaluate_ofFunction X A

/-- The map of singular chain complexes induced by a continuous map. -/
abbrev degreeZeroChainMap {X Y : Type} [TopologicalSpace X] [TopologicalSpace Y]
    (f : C(X, Y)) :
    AlgebraicTopology.SingularCochains.chains X ⟶
      AlgebraicTopology.SingularCochains.chains Y :=
  ((AlgebraicTopology.singularChainComplexFunctor (ModuleCat.{0} ℤ)).obj
    (ModuleCat.of ℤ ℤ)).map (TopCat.ofHom f)

/-- A continuous map takes the `0`-simplex at `x` to the `0`-simplex at `f x`. -/
@[simp]
theorem map_pointSimplex {X Y : Type} [TopologicalSpace X] [TopologicalSpace Y]
    (f : C(X, Y)) (x : X) :
    (TopCat.toSSet.map (TopCat.ofHom f)).app _ (pointSimplex X x) =
      pointSimplex Y (f x) := by
  apply (TopCat.toSSetObj₀Equiv (X := TopCat.of Y)).injective
  rfl

/-- Under the identification of `0`-cochains with functions, pullback along a continuous map is
precomposition. -/
theorem zeroCochainEvaluate_pullback {X Y : Type}
    [TopologicalSpace X] [TopologicalSpace Y] (A : AddCommGrpCat.{0})
    (f : C(X, Y)) (c : NativeCochains Y A 0) :
    zeroCochainEvaluate X A
        ((AlgebraicTopology.SingularCochains.pullback A f).f 0 c) =
      fun x => zeroCochainEvaluate Y A c (f x) := by
  funext x
  change c ((degreeZeroChainMap f).f 0 (simplexChain X (pointSimplex X x))) =
    c (simplexChain Y (pointSimplex Y (f x)))
  apply congrArg c
  have h := ConcreteCategory.congr_hom
    (SSet.ι_chainComplexMap_f (TopCat.toSSet.obj (TopCat.of X))
      (TopCat.toSSet.obj (TopCat.of Y))
      (TopCat.toSSet.map (TopCat.ofHom f)) (ModuleCat.of ℤ ℤ)
      (pointSimplex X x)) 1
  change (degreeZeroChainMap f).f 0 (simplexChain X (pointSimplex X x)) =
    simplexChain Y
      ((TopCat.toSSet.map (TopCat.ofHom f)).app _ (pointSimplex X x)) at h
  rw [map_pointSimplex] at h
  exact h

/-- Evaluation at points, as a morphism from the degree-zero singular-cochain presheaf to the
presheaf of all `A`-valued functions. -/
def zeroCochainEvaluationHom (X : TopCat.{0}) (A : AddCommGrpCat.{0}) :
    presheaf X A 0 ⟶ TopCat.FunctionSheaf.presheaf X A where
  app U := AddCommGrpCat.ofHom (zeroCochainEvaluate U.unop A)
  naturality U V i := by
    apply AddCommGrpCat.hom_ext
    apply AddMonoidHom.ext
    intro c
    change zeroCochainEvaluate V.unop A
      ((AlgebraicTopology.SingularCochains.pullback A
        ((Opens.toTopCat X).map i.unop).hom).f 0 c) =
      fun x : V.unop => zeroCochainEvaluate U.unop A c (i.unop x)
    exact zeroCochainEvaluate_pullback A ((Opens.toTopCat X).map i.unop).hom c

/-- A singular `0`-cochain is determined by its values at points. -/
theorem zeroCochainEvaluate_injective (X : Type) [TopologicalSpace X]
    (A : AddCommGrpCat.{0}) : Function.Injective (zeroCochainEvaluate X A) := by
  intro c d h
  rw [← zeroCochainOfFunction_evaluate X A c,
    ← zeroCochainOfFunction_evaluate X A d, h]

/-- The inverse morphism, turning a function on each open into a `0`-cochain there. -/
def zeroCochainEvaluationInv (X : TopCat.{0}) (A : AddCommGrpCat.{0}) :
    TopCat.FunctionSheaf.presheaf X A ⟶ presheaf X A 0 where
  app U := AddCommGrpCat.ofHom (zeroCochainOfFunction U.unop A)
  naturality U V i := by
    apply AddCommGrpCat.hom_ext
    apply AddMonoidHom.ext
    intro f
    change zeroCochainOfFunction V.unop A (fun x : V.unop => f (i.unop x)) =
      (AlgebraicTopology.SingularCochains.pullback A
        ((Opens.toTopCat X).map i.unop).hom).f 0
          (zeroCochainOfFunction U.unop A f)
    apply zeroCochainEvaluate_injective V.unop A
    rw [zeroCochainEvaluate_ofFunction]
    symm
    calc
      zeroCochainEvaluate V.unop A
          ((AlgebraicTopology.SingularCochains.pullback A
            ((Opens.toTopCat X).map i.unop).hom).f 0
              (zeroCochainOfFunction U.unop A f)) =
        fun x => zeroCochainEvaluate U.unop A
          (zeroCochainOfFunction U.unop A f)
            (((Opens.toTopCat X).map i.unop).hom x) :=
        zeroCochainEvaluate_pullback A ((Opens.toTopCat X).map i.unop).hom
          (zeroCochainOfFunction U.unop A f)
      _ = fun x : V.unop => f (i.unop x) := by
        rw [zeroCochainEvaluate_ofFunction]
        rfl

/-- `S^0(·; A) ≅ A^(·)`: the degree-zero singular-cochain presheaf is the presheaf of all
`A`-valued functions (Bredon III §1; Warner 5.31). -/
def zeroCochainPresheafIsoFunctions (X : TopCat.{0}) (A : AddCommGrpCat.{0}) :
    presheaf X A 0 ≅ TopCat.FunctionSheaf.presheaf X A where
  hom := zeroCochainEvaluationHom X A
  inv := zeroCochainEvaluationInv X A
  hom_inv_id := by
    apply NatTrans.ext
    funext U
    apply AddCommGrpCat.hom_ext
    apply AddMonoidHom.ext
    intro c
    exact zeroCochainOfFunction_evaluate U.unop A c
  inv_hom_id := by
    apply NatTrans.ext
    funext U
    apply AddCommGrpCat.hom_ext
    apply AddMonoidHom.ext
    intro f
    exact zeroCochainEvaluate_ofFunction U.unop A f

end TopCat.SingularCochainSheaf
