/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Lib.Topology.Sheaves.SingularCochainSheaf.GlobalKernelLocal
public import Lib.Topology.Sheaves.SingularCochainSheaf.GlobalUnitH1Criterion

/-!
# Detecting the global-unit kernel on cover-small chains

The kernel of the actual global sheafification unit is exactly local vanishing.  Native simplex
bases turn that statement into vanishing after restriction to the chain complex generated by
simplices carried by a point-indexed open cover.
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false

noncomputable section

open CategoryTheory Opposite Set TopologicalSpace

namespace TopCat.SingularCochainSheaf

open AlgebraicTopology.SingularCochains

/-- Cover-small restriction is zero exactly when all carried simplex values vanish. -/
theorem cochainRestriction_eq_zero_iff {X : Type} [TopologicalSpace X]
    {ι : Type} (A : AddCommGrpCat.{0}) (U : ι → Set X) (n : ℕ)
    (phi : Cochains X A n) :
    (TopCat.SingularSmallChains.cochainRestriction A U).f n phi = 0 ↔
      ∀ sigma : TopCat.SingularSmallChains.SingularSimplex X n,
        TopCat.SingularSmallChains.IsSmallSimplex U sigma →
          phi (TopCat.SingularSmallChains.simplexChain X n sigma) = 0 := by
  constructor
  · intro h sigma hsigma
    have hv := congrArg
      (fun chi : (AlgebraicTopology.SingularCochains.dualComplex A
          (TopCat.SingularSmallChains.complex U)).X n =>
        (show (((TopCat.SingularSmallChains.complex U).X n : Type) →+ A) from chi)
          ⟨TopCat.SingularSmallChains.simplexChain X n sigma,
            TopCat.SingularSmallChains.simplexChain_mem U n sigma hsigma⟩) h
    exact hv
  · intro h
    let r := (TopCat.SingularSmallChains.cochainRestriction A U).f n phi
    have he : TopCat.SingularSmallChains.addHomToIntLinearMap r = 0 := by
      apply (TopCat.SingularSmallChains.smallChainBasis U n).ext
      intro sigma
      change phi (TopCat.SingularSmallChains.smallChainBasis U n sigma).1 = 0
      rw [TopCat.SingularSmallChains.smallChainBasis_apply_val]
      exact h sigma.1 sigma.2
    change r = 0
    exact congrArg LinearMap.toAddMonoidHom he

variable (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (n : ℕ)

/-- Restriction to cover-small chains vanishes iff the native cochain restricts to zero on every
member of the open family. -/
theorem cochainRestriction_eq_zero_iff_open_restrictions
    {ι : Type} (U : ι → Opens X) (phi : Cochains X A n) :
    (TopCat.SingularSmallChains.cochainRestriction A
      (fun i => (U i : Set X))).f n phi = 0 ↔
      ∀ i, restrictGlobalCochain A n phi (U i) = 0 := by
  constructor
  · intro h i
    apply cochain_ext A n
    intro sigma
    let tau : TopCat.SingularSmallChains.SingularSimplex X n :=
      (⟨Subtype.val, continuous_subtype_val⟩ : C(U i, X)).comp sigma
    have htau : TopCat.SingularSmallChains.IsSmallSimplex
        (fun j => (U j : Set X)) tau := by
      refine ⟨i, ?_⟩
      rintro _ ⟨z, rfl⟩
      exact (sigma z).property
    exact (restrictGlobalCochain_simplex A n phi (U i) sigma).trans
      ((cochainRestriction_eq_zero_iff A (fun j => (U j : Set X)) n phi).mp
        h tau htau)
  · intro h
    apply (cochainRestriction_eq_zero_iff A (fun i => (U i : Set X)) n phi).mpr
    intro sigma hsigma
    obtain ⟨i, hi⟩ := hsigma
    let sigma' := simplexInOpen n sigma (U i) hi
    have hv := congrArg
      (fun psi : Cochains (U i) A n =>
        psi (TopCat.SingularSmallChains.simplexChain (U i) n sigma')) (h i)
    exact (restrictGlobalCochain_simplex A n phi (U i) sigma').symm.trans hv

/-- Vanishing on the chains small for an open cover forces vanishing under the global unit. -/
theorem globalCochainUnit_eq_zero_of_smallRestriction
    {ι : Type} (U : ι → Opens X) (hcover : ∀ x : X, ∃ i, x ∈ U i)
    (phi : Cochains X A n)
    (hphi : (TopCat.SingularSmallChains.cochainRestriction A
      (fun i => (U i : Set X))).f n phi = 0) :
    globalCochainUnit X A n phi = 0 := by
  apply globalCochainUnit_eq_zero_of_local X A n phi
  intro x
  obtain ⟨i, hi⟩ := hcover x
  exact ⟨U i, hi,
    (cochainRestriction_eq_zero_iff_open_restrictions X A n U phi).mp hphi i⟩

/-- Every element of the global-unit kernel vanishes on chains small for some point-indexed open
cover. -/
theorem exists_cover_cochainRestriction_eq_zero (phi : Cochains X A n)
    (hphi : globalCochainUnit X A n phi = 0) :
    ∃ U : X → Opens X, (∀ x : X, x ∈ U x) ∧
      (TopCat.SingularSmallChains.cochainRestriction A
        (fun x => (U x : Set X))).f n phi = 0 := by
  classical
  choose U hxU hU using globalCochainUnit_locally_zero X A n phi hphi
  exact ⟨U, hxU,
    (cochainRestriction_eq_zero_iff_open_restrictions X A n U phi).mpr hU⟩

/-- Exact point-indexed-cover criterion for the global-unit kernel. -/
theorem globalCochainUnit_eq_zero_iff_smallCover (phi : Cochains X A n) :
    globalCochainUnit X A n phi = 0 ↔
      ∃ U : X → Opens X, (∀ x : X, x ∈ U x) ∧
        (TopCat.SingularSmallChains.cochainRestriction A
          (fun x => (U x : Set X))).f n phi = 0 := by
  constructor
  · exact exists_cover_cochainRestriction_eq_zero X A n phi
  · rintro ⟨U, hxU, hU⟩
    exact globalCochainUnit_eq_zero_of_smallRestriction X A n U
      (fun x => ⟨x, hxU x⟩) phi hU

/-- The concrete global-unit kernel supplies the abstract locally-small hypothesis. -/
theorem globalKernelLocallySmall (n : ℕ) : GlobalKernelLocallySmall X A n :=
  exists_cover_cochainRestriction_eq_zero X A n

/-- The concrete local kernel criterion supplies the reverse degree-one hypothesis. -/
theorem smallKernelGlobalOne : SmallKernelGlobalOne X A := by
  intro U hxU phi hphi
  exact globalCochainUnit_eq_zero_of_smallRestriction X A 1 U
    (fun x => ⟨x, hxU x⟩) phi hphi

end TopCat.SingularCochainSheaf
