/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
SPDX-License-Identifier: Apache-2.0
-/
module

public import Lib.Topology.Sheaves.SingularCochainSheaf.Presheaf
public import Lib.Topology.Sheaves.Sheafification
public import Mathlib.CategoryTheory.Sites.ConcreteSheafification
public import Mathlib.CategoryTheory.Sites.LeftExact
public import Mathlib.Topology.Sheaves.Sheafify

/-!
# The sheaf of singular cochains

The sheaf `𝒮^n(·; A)` is the sheaf generated by the presheaf `U ↦ S^n(U; A)` of singular cochains
(Bredon, *Sheaf Theory* III.1).  Sheafification is applied degreewise to the complex of
presheaves, and the sheafification unit is kept as a map of complexes.

## Main definitions

* `TopCat.SingularCochainSheaf.sheaf`, `…complexSheaf`: the sheaf `𝒮^n(·; A)` and its complex.
* `TopCat.SingularCochainSheaf.unit`, `…unitComplex`: the sheafification unit.
-/

@[expose] public section

set_option warningAsError true
set_option autoImplicit false

noncomputable section

open CategoryTheory Opposite TopologicalSpace

namespace TopCat.SingularCochainSheaf

universe u

/-- The sheaf `𝒮^n(·; A)` generated by the presheaf of singular `n`-cochains. -/
abbrev sheaf (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (n : ℕ) :
    TopCat.Sheaf AddCommGrpCat.{0} X :=
  (TopCat.Sheaf.sheafification X).obj (presheaf X A n)

/-- The coboundary `𝒮^i(·; A) → 𝒮^j(·; A)` induced by the singular coboundary. -/
def sheafDifferential (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (i j : ℕ) :
    sheaf X A i ⟶ sheaf X A j :=
  (TopCat.Sheaf.sheafification X).map (differential X A i j)

/-- The complex of sheaves `𝒮^•(·; A)`, the degreewise sheafification of the singular-cochain
complex of presheaves. -/
abbrev complexSheaf (X : TopCat.{0}) (A : AddCommGrpCat.{0}) :
    CochainComplex (TopCat.Sheaf AddCommGrpCat.{0} X) ℕ :=
  ((TopCat.Sheaf.sheafification X).mapHomologicalComplex (ComplexShape.up ℕ)).obj (complex X A)

/-- The degree-`n` term of the complex of sheaves is the sheaf `𝒮^n(·; A)`. -/
@[simp]
theorem complexSheaf_X (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (n : ℕ) :
    (complexSheaf X A).X n = sheaf X A n := rfl

/-- The differential of the complex of sheaves is the sheafified coboundary. -/
@[simp]
theorem complexSheaf_d (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (i j : ℕ) :
    (complexSheaf X A).d i j = sheafDifferential X A i j := rfl

/-- The sheafification unit in degree `n`. -/
def unit (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (n : ℕ) :
    presheaf X A n ⟶ (sheaf X A n).obj :=
  toSheafify (Opens.grothendieckTopology X) (presheaf X A n)

/-- The sheafification units commute with the singular-cochain coboundary. -/
@[reassoc]
theorem unit_d (X : TopCat.{0}) (A : AddCommGrpCat.{0}) (i j : ℕ) :
    unit X A i ≫ (sheafDifferential X A i j).hom =
      differential X A i j ≫ unit X A j :=
  (toSheafify_naturality (Opens.grothendieckTopology X)
    (differential X A i j)).symm

/-- The sheafification unit as a map of full presheaf complexes. -/
def unitComplex (X : TopCat.{0}) (A : AddCommGrpCat.{0}) :
    complex X A ⟶
      ((TopCat.Sheaf.forget AddCommGrpCat.{0} X).mapHomologicalComplex
        (ComplexShape.up ℕ)).obj (complexSheaf X A) where
  f n := unit X A n
  comm' i j _ := unit_d X A i j

end TopCat.SingularCochainSheaf
